### ISSUE TITLE
PyPi tarball contents could be improved in some ways

### ISSUE THREAD

**Issue by lemenkov** [kutoga/lazy-load#2]
Hello and thank you for this library I am using indirectly in my daily work.

I think the PyPi's tarball contents could be improved a bit (no big deal though but still):

- [x] All the files have 0777 access mode (made on Windows?). Should be something like 0644 instead.
- [x] The tests directory is missing. I believe it's better to ship it anyway since somebody (me included) loves to run the tests during installation process.
- [x] LICENSE file is missing. Should be shipped as well.

Thank you for this library once again!

**Comment by kutoga** [comment]
Hey

Thanks a lot for the feedback🙂. This library is only a very small wrapper around `python-lazy-object-proxy` which I needed at some point to do a few things a bit nicer, but 99.9% of its value come from `python-lazy-object-proxy`. However, I'm happy that also other people found some use in it.

Regarding the issues:
Indeed back in the days I've use Windows and likely because of that the files had access mode 0777. This is now fixed. Also the missing tests directory and LICENSE file are now shipped.

https://pypi.org/project/lazy-load/#history

Again, thanks a lot for the feedback:)!
